export const data = [
    {
      model: "Honda Civic",
      year: 2022,
      price: 25000,
      color: ["Red", "Blue", "White"],
      mileage: 38,
      power: 174,
      max_speed: 130,
    },
    {
      model: "Toyota Camry",
      year: 2023,
      price: 30000,
      color: ["Silver", "Black", "Gray"],
      mileage: 39,
      power: 203,
      max_speed: 135,
    },
    {
      model: "Ford Mustang",
      year: 2022,
      price: 40000,
      color: ["Yellow", "Black", "Red"],
      mileage: 28,
      power: 310,
      max_speed: 155,
    },
    {
      model: "Chevrolet Cruze",
      year: 2022,
      price: 22000,
      color: ["Black", "Silver", "Blue"],
      mileage: 38,
      power: 153,
      max_speed: 120,
    },
    {
      model: "BMW X5",
      year: 2023,
      price: 65000,
      color: ["White", "Gray", "Red"],
      mileage: 26,
      power: 335,
      max_speed: 155,
    },
    {
      model: "Audi A4",
      year: 2022,
      price: 42000,
      color: ["Silver", "Black", "Blue"],
      mileage: 32,
      power: 248,
      max_speed: 130,
    },
    {
      model: "Tesla Model 3",
      year: 2022,
      price: 45000,
      color: ["Black", "White", "Red"],
      mileage: 124,
      power: 283,
      max_speed: 145,
    },
    {
      model: "Mercedes-Benz C-Class",
      year: 2023,
      price: 55000,
      color: ["Silver", "Blue", "Gray"],
      mileage: 35,
      power: 255,
      max_speed: 155,
    },
    {
      model: "Volkswagen Golf GTI",
      year: 2022,
      price: 32000,
      color: ["Red", "Black", "White"],
      mileage: 32,
      power: 228,
      max_speed: 155,
    },
  ];
  
  // {
  //   "image": "https://img.freepik.com/premium-vector/small-modern-honda-brio-car-illustration_387989-705.jpg?ga=GA1.2.978443669.1704357159&semt=ais_hybrid",
  //   "odometer": 35000,
  //   "scratches": 5,
  //   "original_paint": "Red",
  //   "reported_accident": 0,
  //   "previous_buyer": 1,
  //   "registration_place": "California", 
  //   "description": ["Excellent condition", "No accidents", "Low mileage"],
  //   "title": "Honda Civic 2022"
  // }