//For Authentication...
export const LOGIN_POST_REQUEST= "LOGIN_POST_REQUEST";
export const LOGIN_POST_SUCCESS= "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE= "LOGIN_POST_FAILURE";
export const REGISTER_POST_SUCCESS= "LOGIN_POST_SUCCESS";

// Inventory Action Types
export const FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST";
export const FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS";
export const FETCH_INVENTORY_FAILURE = "FETCH_INVENTORY_FAILURE";
export const ADD_INVENTORY = "ADD_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";

// OEM Action Types
export const FETCH_OEM_REQUEST = "FETCH_OEM_REQUEST";
export const FETCH_OEM_SUCCESS = "FETCH_OEM_SUCCESS";
export const FETCH_OEM_FAILURE = "FETCH_OEM_FAILURE";
export const ADD_OEM = "ADD_OEM";
